### ISSUE TITLE
Remove mirror

### ISSUE THREAD

**Issue by enoch85** [jblakeman/apt-select#56]
I'm one of the maintainers of the @nextcloud [VM](https://github.com/nextcloud/vm) and we use apt-select in our script to adapt the mirrors to the location our users are in. 

Though I got a report that `http://ftp.availo.se/ubuntu` doesn't fetch (or even contains) all packages and therefore the installation fails.

So, please remove it.

**Comment by jblakeman** [comment]
This doesn't sound like something apt-select can control since the list of mirrors is pulled straight from [mirrors.txt](http://mirrors.ubuntu.com/mirrors.txt), with status information being pulled from [Launchpad](https://launchpad.net/ubuntu/+archivemirrors).  Availo is currently [listed as an official mirror](https://launchpad.net/ubuntu/+mirror/ftp.availo.se-archive).

Without more information such as error output that might be specific to apt-select's behavior I'm afraid I'm not sure how I can help here.

**Comment by enoch85** [comment]
Aah ok. Let's close this then.
