### ISSUE TITLE
Fails to create new sources.list if current one use mirror protocol

### ISSUE THREAD

**Issue by solsticedhiver** [jblakeman/apt-select#72]
With (newer ?) ubuntu release, one can use a **mirror** **protocol** that use directly the mirrors from _mirrors.ubuntu.com_

Tihs means lines in sources.list looks like this:

    deb mirror://mirrors.ubuntu.com/mirrors.txt [...]

When this is set in sources.list, then `apt-select` bails out with the error:

    Traceback (most recent call last):
      File "/home/solstice/.local/bin/apt-select", line 11, in <module>
        sys.exit(main())
      File "/home/solstice/.local/lib/python2.7/site-packages/apt_select/__main__.py", line 244, in main
        apt_select()
      File "/home/solstice/.local/lib/python2.7/site-packages/apt_select/__main__.py", line 175, in apt_select
        sources.set_current_archives()
      File "/home/solstice/.local/lib/python2.7/site-packages/apt_select/apt.py", line 164, in set_current_archives
        self.skip_gen_msg)
    apt_select.apt.SourcesFileError: Error finding current main URI in /etc/apt/sources.list
    Skipping file generation

**Comment by jblakeman** [comment]
@solsticedhiver Happy to hear you are using the script. However, if that is the only line in your file with a `deb` or `deb-src` definition, it will not work.

`apt-select` is meant to be a better alternative to the `mirrors://` method in that it tests latency. It does not support generating a new `sources.list` from scratch. The file generation is meant to replace existing mirror definitions with better ones. `mirror://mirrors.ubuntu.com/mirrors.txt` is not actually a valid mirror because `mirror` is not a supported scheme (see `man sources.list` -> URI Specification, and the list of supported URI schemes in the` README`). Please try using the script with mirror definitions line like:

`deb http://archive.ubuntu.com/ubuntu/ bionic main restricted`

Thanks!

Close duplicate to #3.

**Comment by jblakeman** [comment]
@solsticdhiver ok so by “newer” you mean 18.10 cosmic. That is the only distribution that specifies mirror as a scheme.

I’m not sure what “Software and mirrors” is, but that’s irrelevant because `apt-select` and `mirror` scheme work on conflicting ideas.

According to the man page it represent the location of a mirror *list* so it wouldn’t make sense for `apt-select` to assume that it should be replaced by some single http mirror.

**Comment by solsticedhiver** [comment]
OK. I understand.

But I don't see the big deal given that you create a new sources.list and do not replace the exisitng one.
And why not replace a mirror://something with a http:// if the mirror given is bad and you get a better one with apt-select test ?
